---
title: "Modeling with H2O"
output: html_document
---


```{r load packages}
library(tidyverse)
library(h2o)
library(assertr)
library(naniar)
library(rsample)
```

#Read in data
```{r read in the data}
lumbar_df <- read_csv("~/Desktop/lumbar_full_df.csv") %>% 
  verify(has_all_names("fake_id", "odi_percent_1yr")) %>% 
  assert(is_uniq("fake_id")) %>% 
  assert(not_na, fake_id) %>% 
  assert(within_bounds(-10, 100), odi_q1_1yr)

lumbar_age_weight_height <- read_csv("~/Desktop/lumbar_age_weight_height.csv", 
    col_types = cols(fake_id = col_character())) %>% 
  verify(has_all_names("fake_id")) %>% 
  assert(is_uniq("fake_id")) %>% 
  assert(not_na, fake_id)

# deal with problems
lumbar_df_new_id <- lumbar_df %>%
  mutate(new_id = str_replace(fake_id, "000", ""))
```

#Join data
```{r join the data}
lumbar_full_df <- inner_join(lumbar_df_new_id, lumbar_age_weight_height, by = c("new_id" = "fake_id"))
```

```{r variables to select}
lumbar_final <- lumbar_full_df %>%
  select(-contains("cpt")) %>% 
  #This is a formula function
  select_if( ~ pct_miss(.) < 5) %>% 
  drop_na()

# Variables we want to select
variables_to_select <- c("odi_percent_1yr",
                         "odi_percent_preop",
                         "gender", 
                         "race", 
                         "age", 
                         "diabetes",
                         "smoker", 
                         "employment", 
                         "height", 
                         "weight",
                         "median_household_income",
                         "asthma")

# Create new data set with just the variables we want
lumbar_final <- lumbar_final %>%
  select(variables_to_select)
```

```{r initialize h2o}
h2o.init()
```

```{r split the model frames}
set.seed(42)
lumbar_split <- lumbar_final %>% initial_split(prop = 0.80)
lumbar_training <- lumbar_split %>% training()
lumbar_testing <- lumbar_split %>% testing()
```

```{r training the model}
lumbar_training_h2o <- as.h2o(lumbar_training)

gbm_odi <- h2o.gbm(
  y = "odi_percent_1yr",
  training_frame = lumbar_training_h2o,
  nfolds = 10,
  seed = 42) 

```

```{r}
h2o.varimp_plot(gbm_odi, num_of_features = 5)
```

##Red cap pull
```{r}
library(redcapAPI)
# changing code here
rcon <- redcapConnection(
  url = "https://redcap.vanderbilt.edu/api/",
  token = "0BD69368A4205525F270847A68578180")
```

```{r}
report_patient_id_df <- exportReports(rcon, report_id = 164029) %>%
  select(mrn, gender, race) %>%
  mutate_all(type.convert) %>%
  mutate(mrn = as.character(mrn))

report_baseline_df <- exportReports(rcon, report_id = 164027) %>%
  mutate_all(type.convert) %>%
  mutate(mrn = as.character(mrn))
```

